/** @type {import('next').NextConfig} */
const nextConfig = {
  serverExternalPackages: ["@prisma/client", "prisma"],
  transpilePackages: [
    "@cookunity-seo-agent/core",
    "@cookunity-seo-agent/shared",
    "@cookunity-seo-agent/prompts",
    "@cookunity-seo-agent/integrations",
    "@cookunity-seo-agent/db",
  ],
  outputFileTracingIncludes: {
    "/*": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/agents": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/grid": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/review": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/agents/[agentName]/rerun": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/grid/rows": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/workflow/run": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/opportunities": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/opportunities/[opportunityId]": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/opportunities/[opportunityId]/run": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/opportunities/[opportunityId]/publish": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/opportunities/[opportunityId]/steps/[stepName]/run": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/workflow/steps/[stepRunId]/approve": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/workflow/steps/[stepRunId]/revision": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/workflow/steps/[stepRunId]/rerun": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
    "/api/workflow/steps/[stepRunId]/edit": [
      "../../packages/prompts/brand/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/.prisma/client/**/*",
      "../../node_modules/.pnpm/@prisma+client@*/node_modules/@prisma/client/**/*",
      "../../node_modules/.pnpm/prisma@*/node_modules/prisma/**/*",
      "../../node_modules/.prisma/client/**/*",
    ],
  },
};

export default nextConfig;
