import { z } from "zod";
declare const envSchema: z.ZodObject<{
    NODE_ENV: z.ZodDefault<z.ZodEnum<["development", "test", "production"]>>;
    APP_MODE: z.ZodDefault<z.ZodEnum<["mock", "live"]>>;
    ADMIN_EMAIL: z.ZodDefault<z.ZodString>;
    ADMIN_PASSWORD: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_APP_NAME: z.ZodDefault<z.ZodString>;
    NEXT_PUBLIC_BASE_URL: z.ZodDefault<z.ZodString>;
    DATABASE_URL: z.ZodDefault<z.ZodString>;
    REDIS_URL: z.ZodDefault<z.ZodString>;
    OPENAI_API_KEY: z.ZodOptional<z.ZodString>;
    OPENAI_MODEL: z.ZodDefault<z.ZodString>;
    AHREFS_API_KEY: z.ZodOptional<z.ZodString>;
    AHREFS_BASE_URL: z.ZodDefault<z.ZodString>;
    AHREFS_COUNTRY: z.ZodDefault<z.ZodString>;
    GSC_CLIENT_EMAIL: z.ZodOptional<z.ZodString>;
    GSC_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    GSC_SITE_URL: z.ZodDefault<z.ZodString>;
    GA4_PROPERTY_ID: z.ZodOptional<z.ZodString>;
    GOOGLE_TRENDS_GEO: z.ZodDefault<z.ZodString>;
    GOOGLE_SERVICE_ACCOUNT_EMAIL: z.ZodOptional<z.ZodString>;
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY: z.ZodOptional<z.ZodString>;
    GOOGLE_DRIVE_REVIEW_FOLDER_ID: z.ZodOptional<z.ZodString>;
    GOOGLE_DOCS_REVIEW_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodEnum<["true", "false"]>>, boolean, "true" | "false" | undefined>;
    SERP_API_KEY: z.ZodOptional<z.ZodString>;
    SERP_PROVIDER: z.ZodDefault<z.ZodString>;
    SEMRUSH_API_KEY: z.ZodOptional<z.ZodString>;
    SEMRUSH_BASE_URL: z.ZodDefault<z.ZodString>;
    STRAPI_BASE_URL: z.ZodDefault<z.ZodString>;
    STRAPI_API_TOKEN: z.ZodOptional<z.ZodString>;
    STRAPI_COLLECTION: z.ZodDefault<z.ZodString>;
    STRAPI_DOCUMENT_ID_FIELD: z.ZodDefault<z.ZodString>;
    STRAPI_ENTRY_ID_FIELD: z.ZodDefault<z.ZodString>;
    STRAPI_FIELD_MAPPING_JSON: z.ZodDefault<z.ZodString>;
    ANALYTICS_PROVIDER: z.ZodDefault<z.ZodString>;
    ANALYTICS_API_KEY: z.ZodOptional<z.ZodString>;
    OTEL_EXPORTER_OTLP_ENDPOINT: z.ZodOptional<z.ZodString>;
    SLACK_ALERT_WEBHOOK: z.ZodOptional<z.ZodString>;
    PUBLISH_ENABLED: z.ZodEffects<z.ZodDefault<z.ZodEnum<["true", "false"]>>, boolean, "true" | "false" | undefined>;
    ENABLE_MOCK_DATA: z.ZodEffects<z.ZodDefault<z.ZodEnum<["true", "false"]>>, boolean, "true" | "false" | undefined>;
    DISCOVERY_CRON: z.ZodDefault<z.ZodString>;
    MONITORING_CRON: z.ZodDefault<z.ZodString>;
    REFRESH_CRON: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "test" | "production";
    APP_MODE: "mock" | "live";
    ADMIN_EMAIL: string;
    ADMIN_PASSWORD: string;
    NEXT_PUBLIC_APP_NAME: string;
    NEXT_PUBLIC_BASE_URL: string;
    DATABASE_URL: string;
    REDIS_URL: string;
    OPENAI_MODEL: string;
    AHREFS_BASE_URL: string;
    AHREFS_COUNTRY: string;
    GSC_SITE_URL: string;
    GOOGLE_TRENDS_GEO: string;
    GOOGLE_DOCS_REVIEW_ENABLED: boolean;
    SERP_PROVIDER: string;
    SEMRUSH_BASE_URL: string;
    STRAPI_BASE_URL: string;
    STRAPI_COLLECTION: string;
    STRAPI_DOCUMENT_ID_FIELD: string;
    STRAPI_ENTRY_ID_FIELD: string;
    STRAPI_FIELD_MAPPING_JSON: string;
    ANALYTICS_PROVIDER: string;
    PUBLISH_ENABLED: boolean;
    ENABLE_MOCK_DATA: boolean;
    DISCOVERY_CRON: string;
    MONITORING_CRON: string;
    REFRESH_CRON: string;
    OPENAI_API_KEY?: string | undefined;
    AHREFS_API_KEY?: string | undefined;
    GSC_CLIENT_EMAIL?: string | undefined;
    GSC_PRIVATE_KEY?: string | undefined;
    GA4_PROPERTY_ID?: string | undefined;
    GOOGLE_SERVICE_ACCOUNT_EMAIL?: string | undefined;
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?: string | undefined;
    GOOGLE_DRIVE_REVIEW_FOLDER_ID?: string | undefined;
    SERP_API_KEY?: string | undefined;
    SEMRUSH_API_KEY?: string | undefined;
    STRAPI_API_TOKEN?: string | undefined;
    ANALYTICS_API_KEY?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SLACK_ALERT_WEBHOOK?: string | undefined;
}, {
    NODE_ENV?: "development" | "test" | "production" | undefined;
    APP_MODE?: "mock" | "live" | undefined;
    ADMIN_EMAIL?: string | undefined;
    ADMIN_PASSWORD?: string | undefined;
    NEXT_PUBLIC_APP_NAME?: string | undefined;
    NEXT_PUBLIC_BASE_URL?: string | undefined;
    DATABASE_URL?: string | undefined;
    REDIS_URL?: string | undefined;
    OPENAI_API_KEY?: string | undefined;
    OPENAI_MODEL?: string | undefined;
    AHREFS_API_KEY?: string | undefined;
    AHREFS_BASE_URL?: string | undefined;
    AHREFS_COUNTRY?: string | undefined;
    GSC_CLIENT_EMAIL?: string | undefined;
    GSC_PRIVATE_KEY?: string | undefined;
    GSC_SITE_URL?: string | undefined;
    GA4_PROPERTY_ID?: string | undefined;
    GOOGLE_TRENDS_GEO?: string | undefined;
    GOOGLE_SERVICE_ACCOUNT_EMAIL?: string | undefined;
    GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?: string | undefined;
    GOOGLE_DRIVE_REVIEW_FOLDER_ID?: string | undefined;
    GOOGLE_DOCS_REVIEW_ENABLED?: "true" | "false" | undefined;
    SERP_API_KEY?: string | undefined;
    SERP_PROVIDER?: string | undefined;
    SEMRUSH_API_KEY?: string | undefined;
    SEMRUSH_BASE_URL?: string | undefined;
    STRAPI_BASE_URL?: string | undefined;
    STRAPI_API_TOKEN?: string | undefined;
    STRAPI_COLLECTION?: string | undefined;
    STRAPI_DOCUMENT_ID_FIELD?: string | undefined;
    STRAPI_ENTRY_ID_FIELD?: string | undefined;
    STRAPI_FIELD_MAPPING_JSON?: string | undefined;
    ANALYTICS_PROVIDER?: string | undefined;
    ANALYTICS_API_KEY?: string | undefined;
    OTEL_EXPORTER_OTLP_ENDPOINT?: string | undefined;
    SLACK_ALERT_WEBHOOK?: string | undefined;
    PUBLISH_ENABLED?: "true" | "false" | undefined;
    ENABLE_MOCK_DATA?: "true" | "false" | undefined;
    DISCOVERY_CRON?: string | undefined;
    MONITORING_CRON?: string | undefined;
    REFRESH_CRON?: string | undefined;
}>;
export type AppConfig = z.infer<typeof envSchema>;
export declare function getConfig(overrides?: Partial<NodeJS.ProcessEnv>): AppConfig;
export {};
